In [1]:
import pandas as pd
import numpy as np
from LambdaRankNN import LambdaRankNN

In [ ]:
# define variables 
DATA =  "../../data/set_neg_zero_aff1_down.csv"
col_remove = True 
n_train = 300000
n_test = 100000
n_trees = 10
learning_rate = 0.01

In [2]:
TRAIN_DATA = "../data/set_neg_zero_aff1.csv"

# Read the data into memory
training_data = pd.read_csv(TRAIN_DATA,nrows= 2500000)
validation_data = pd.read_csv(TRAIN_DATA,skiprows=2500000,nrows = 1000000, header=None, names= training_data.columns)
test_data = pd.read_csv(TRAIN_DATA,skiprows= 3500000,nrows = 1000000, header=None,names= training_data.columns)

col_names = list(training_data.columns)
col_names.remove('click_bool')
col_names.remove('booking_bool')
col_names.remove('srch_id')
col_names.remove('gross_bookings_usd')
col_names.remove('date_time')

# A relevance function to define the relevance score for NDCG
def relevance(a):
    if a[0] == a[1] == 1:
        return 5
    elif a[0] == 1 and a[1] == 0:
        return 1
    else:
        return 0

In [3]:
X_train = training_data[col_names].values
y_train = training_data.iloc[:,-2:].apply(relevance,axis = 1)
q_train = training_data.srch_id

X_test = test_data[col_names].values
y_test = test_data.iloc[:,-2:].apply(relevance,axis = 1)
q_test = test_data.srch_id

In [4]:
X = X_train
y = np.array(y_train)
q = np.array(q_train)
print(X.shape, y.shape, q.shape)

(2500000, 49) (2500000,) (2500000,)


In [5]:
print(X.shape)

(2500000, 49)


In [6]:
# train model
ranker = LambdaRankNN(input_size=X.shape[1], hidden_layer_sizes=(16,8,), activation=('relu', 'relu',), solver='adam')
ranker.fit(X, y, q, epochs=1)

ValueError: Expect x to be a non-empty array or dataset.

In [62]:
y_pred = ranker.predict(X)
ranker.evaluate(X, y, q, eval_at=38)

ndcg@38: 0.4926595289099743


In [63]:
print(y_pred)

[-5.982824  -5.9920287 -5.747039  ... -4.3107195 -2.9092398 -2.6455505]


In [64]:
X_test = X_test
y_test = np.array(y_test)
q_test = np.array(q_test)
print(X_test.shape, y_test.shape, q_test.shape)

(1000000, 49) (1000000,) (1000000,)
[[  5. 219. -10. ...   0.   0.   0.]
 [  5. 219. -10. ...   0.   0.   0.]
 [  5. 219. -10. ...   0.   0.   0.]
 ...
 [  5. 219. -10. ...   0.   0.   0.]
 [  5. 219. -10. ...   0.   0.   0.]
 [  5. 219. -10. ...   1.   0.  10.]]


In [61]:
y_test_pred = ranker.predict(X_test)

# ranker.evaluate(X_test, y_test, q_test, eval_at=38)

print(len(y_test_pred))

1000000
