In [1]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
import torch

In [2]:
# load dataset
#dataset = "dataframe_normalized_outliers_removed.csv" 
dataset = "dataframe_standardized_outliers_removed_classes.csv"
#dataset = "dataframe_new.csv"  ## debug
df = pd.read_csv(dataset) # dataframe in pandas


#df = df[df['target'] != 7] # debug check if it learns to predict not only 7
df['target'] = df['target'].sub(3)# change to 7 classes 0 1 2 3 4 5 6
#df = df[df['target'] != 7]
df

Unnamed: 0    no  target  t  activity  appCat.builtin  \
0              0     1       4  0  0.641645        1.103108   
1              1     1       4  1  1.074310       -0.242798   
2              2     1       4  2  0.065088        0.067334   
3              3     1       4  3 -0.085503       -0.167041   
4              4     2       4  0  1.074310       -0.242798   
...          ...   ...     ... ..       ...             ...   
4191        4191  1048       4  3  0.272023        0.774332   
4192        4192  1049       4  0 -0.328753       -0.065428   
4193        4193  1049       4  1 -1.058736       -0.245614   
4194        4194  1049       4  2  0.272023        0.774332   
4195        4195  1049       4  3  1.242266       -0.428041   

      appCat.communication  appCat.entertainment  appCat.finance  appCat.game  \
0                 1.636492              0.244791        1.129913    -0.259976   
1                 1.062958             -0.575133        0.292739    -0.259976   
2                 1.182367             -0.574217        0.949321    -0.259976   
3                 2.937521              0.217447        0.675919    -0.259976   
4                 1.062958             -0.575133        0.292739    -0.259976   
...                    ...                   ...             ...          ...   
4191             -0.254069             -0.107484       -0.327054    -0.259976   
4192             -0.559067             -0.041053       -0.327054    -0.259976   
4193             -0.192281             -0.546996       -0.327054    -0.259976   
4194             -0.254069             -0.107484       -0.327054    -0.259976   
4195             -0.907386             -0.536193       -0.327054    -0.259976   

      ...  appCat.travel  appCat.unknown  appCat.utilities  appCat.weather  \
0     ...       4.689448       -0.322651          7.439909       -0.230130   
1     ...      -0.207470       -0.322651          1.198651       -0.230130   
2     ...      -0.415500       -0.322651          0.063147        2.406086   
3     ...       1.925529       -0.322651          1.991383       -0.230130   
4     ...      -0.207470       -0.322651          1.198651       -0.230130   
...   ...            ...             ...               ...             ...   
4191  ...      -0.415500       -0.322651          0.070671       -0.230130   
4192  ...      -0.415500       -0.322651         -0.327129       -0.230130   
4193  ...      -0.415500       -0.322651          0.401548       -0.230130   
4194  ...      -0.415500       -0.322651          0.070671       -0.230130   
4195  ...      -0.410263       -0.322651         -0.285631       -0.230130   

          call  circumplex.arousal  circumplex.valence      mood    screen  \
0     1.319838            0.485487           -1.266137 -1.209901  2.770542   
1     0.287520            1.143750           -0.496733 -0.899697  0.106958   
2    -0.744797            0.485487            0.272670 -0.279289  0.249101   
3     2.696262            1.472881           -1.779072 -1.520105  2.110863   
4     0.287520            1.143750           -0.496733 -0.899697  0.106958   
...        ...                 ...                 ...       ...       ...   
4191  2.696262            0.156356            1.298542  1.892137  1.947385   
4192  2.696262           -0.501907           -1.779072 -2.450716  2.983480   
4193 -0.400691           -0.831038           -0.753201 -1.209901 -0.354860   
4194  2.696262            0.156356            1.298542  1.892137  1.947385   
4195  0.975732           -2.037854            0.785606  0.030914 -0.471995   

           sms  
0    -0.497599  
1     0.147818  
2    -0.497599  
3    -0.497599  
4     0.147818  
...        ...  
4191  0.147818  
4192  1.438652  
4193  0.793235  
4194  0.147818  
4195  0.147818  

[4196 rows x 23 columns]

In [3]:
df[df['target'] == 7]

Empty DataFrame
Columns: [Unnamed: 0, no, target, t, activity, appCat.builtin, appCat.communication, appCat.entertainment, appCat.finance, appCat.game, appCat.office, appCat.other, appCat.social, appCat.travel, appCat.unknown, appCat.utilities, appCat.weather, call, circumplex.arousal, circumplex.valence, mood, screen, sms]
Index: []

[0 rows x 23 columns]

In [4]:
print(df[df['no'] == 723])
for i in range(720, 730):  ### debug
    df = df[df['no'] != i]
print(df[df['no'] == 723])
df = df.sample(frac=1) # shuffle

      Unnamed: 0   no  target  t  activity  appCat.builtin  \
2888        2888  723       4  0 -0.499064       -0.032645   
2889        2889  723       4  1  0.989888        0.949300   
2890        2890  723       4  2  0.457188        0.335828   
2891        2891  723       4  3 -0.154787       -0.272890   

      appCat.communication  appCat.entertainment  appCat.finance  appCat.game  \
2888              0.554783             -0.628182       -0.327054    -0.259976   
2889              0.538962             -0.513537       -0.327054    -0.259976   
2890             -0.591393             -0.658839       -0.327054    -0.259976   
2891             -0.855933             -0.658839       -0.327054    -0.259976   

      ...  appCat.travel  appCat.unknown  appCat.utilities  appCat.weather  \
2888  ...        -0.4155       -0.322651         -0.089520        -0.23013   
2889  ...        -0.4155        0.060803         -0.166846        -0.23013   
2890  ...        -0.4155       -0.322651         

In [19]:
# get labels
Y = df['target'].to_numpy()
Y = Y[::4]
len(Y)

1039

In [6]:
# get input 
X = df.iloc[:, 3:].to_numpy()
X = X[:, 1:]
split = len(X[:, 0]) / 4
X = np.array_split(X, split)


In [7]:
# split train and test set
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=123, shuffle=False)


In [ ]:
# k-fold cross validation
from sklearn import cross_validation
kf = cross_validation.KFold(1039, n_folds=10)

In [8]:
batch_size = 16
def batch_generator(X, Y, batch_size):
    batchesx = []
    batchesy = []
    batchx = [] # batches
    batchy = []
    for i in range(len(X)):
        batchx.append(X[i]) # add to batch
        batchy.append(Y[i])
        #print(batchy)
        if i % batch_size == 0: # batch full?
            batchesx.append([batchx])
            batchesy.append([batchy])
            batchx = [] # batches
            batchy = []
    print(batchesy)
    return batchesx, batchesy


In [9]:
# to torch tensor
x_train = torch.tensor(x_train)
#x_train = x_train[:724]#### debug
#for i in range(710, 730):  ### debug
    #np.delete(x_train, i)
    #np.delete(y_train, i)
#x_train = x_train[4:] ## debug
y_train = torch.tensor(y_train).to(torch.int64)
#print(x_train[724])
#print(y_train[724])

In [10]:
x_test = torch.tensor(x_test)
y_test = torch.tensor(y_test).to(torch.int64)

In [11]:
#print(x_train[728])
#print(y_train[728])

In [12]:
# training on GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)


cpu


In [13]:
import torch.nn as nn
import torch.nn.functional as F

class lstm(nn.Module):
    def __init__ (self, input_size, hidden_size, num_layers, seq_length, output_size):
        super(). __init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.seq_length = seq_length
        self.output_size = output_size
        self.hidden_lin_size = 20
        
        self.ltsm = torch.nn.LSTM(self.input_size, self.hidden_size, batch_first=True) 
        #self.dropout = torch.nn.Dropout(0.3)
        self.lin1 = nn.Linear(self.hidden_size, self.hidden_lin_size) 
        self.lin2 = nn.Linear(self.hidden_lin_size, self.output_size)
    def forward(self, x):
        x, (hn, cn) = self.ltsm(x)
        #x  = self.dropout(x)
        x = F.relu(x) # is this ok?
        x = F.relu(self.lin1(x))  
        x = self.lin2(x)
        return x, (hn, cn)
net = lstm(input_size=19, hidden_size=100, num_layers=1, seq_length=4, output_size=7).float()

In [21]:
# weighted cross entropy
unique, counts = np.unique(y_train, return_counts=True)
print(unique)
print(counts)
nSamples = [887, 6130, 480, 317, 972, 101, 128]
normedWeights = [(1 - (x / sum(counts))) for x in counts]
normedWeights = torch.FloatTensor(normedWeights).to(device)
normedWeights
# way 2
#normedWeights = counts / sum(counts)
#normedWeights = torch.FloatTensor(normedWeights).to(device)
#normedWeights

[0 1 2 3 4 5 6]
[  1   9  18 189 414 189  11]


tensor([0.9988, 0.9892, 0.9783, 0.7726, 0.5018, 0.7726, 0.9868])

In [15]:
import torch.optim as optim

learning_rate = 0.001
#criterion =  nn.MSELoss()    # MSE for regression
criterion = nn.CrossEntropyLoss(weight=normedWeights)
optimizer = optim.Adam(net.parameters(), lr=learning_rate)

In [16]:
target = torch.randint(0, 10, (10,))
one_hot = torch.nn.functional.one_hot(target)

In [17]:
# train the network

n = 10 # for one hot

for epoch in range(5):
    running_loss = 0.0
    net.train()
    for i in range(len(x_train)):
        
        # get the inputs
        #print(torch.unsqueeze(x_train[i], 0))
        inputs, labels =torch.unsqueeze(x_train[i], 0).to(device).float(), torch.unsqueeze(y_train[i], 0).to(device)
        labels_onehot = torch.nn.functional.one_hot(labels[0].to(torch.int64), n)
        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs, (hn, cn) = net(inputs)
        #print(outputs)
        output = torch.mean(outputs, dim=1) # takes the average over the outputs 
        #output = outputs[3] # takes the last, (does that makes more sense)
        
        #print(output[0])
        #print(labels[0])
        loss = criterion(output, labels)
        loss.backward() 
        optimizer.step()
        #print(i, loss.item())
        # running loss
        running_loss += loss.item()
        #print(i, loss.item())
        # statistics tensorboard
        if i % 100 == 99:    # every 30 mini-batches

            # print
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 100))
            
            '''
            # ...log the running loss
            writer.add_scalar('training loss',
                            running_loss / 30,
                            epoch * len(x_train) + i)
            '''
            running_loss = 0.0
'''
    # run on validation set
    net.eval()
    for j, data in enumerate(x_val, 0):
        inputs, labels = x_val[j].to(device), y_val[j].to(device)
        
        # calculate outputs and loss
        outputs, (hn, cn) = net(inputs)
        output = torch.mean(outputs, dim=1)  
        loss = criterion(output, labels)
        
        # running loss
        running_loss += loss.item()
        
    # add to tensorboard
    writer.add_scalar('validation_loss',
                            running_loss / j,
                            epoch)
    print("validation loss:", running_loss / j, j)
'''
print('Finished Training')

[1,   100] loss: 1.649
[1,   200] loss: 1.269
[1,   300] loss: 1.185
[1,   400] loss: 1.361
[1,   500] loss: 1.154
[1,   600] loss: 1.277
[1,   700] loss: 1.211
[1,   800] loss: 1.206
[2,   100] loss: 1.204
[2,   200] loss: 1.192
[2,   300] loss: 1.169
[2,   400] loss: 1.283
[2,   500] loss: 1.136
[2,   600] loss: 1.253
[2,   700] loss: 1.195
[2,   800] loss: 1.174
[3,   100] loss: 1.163
[3,   200] loss: 1.146
[3,   300] loss: 1.143
[3,   400] loss: 1.200
[3,   500] loss: 1.105
[3,   600] loss: 1.219
[3,   700] loss: 1.182
[3,   800] loss: 1.113
[4,   100] loss: 1.110
[4,   200] loss: 1.101
[4,   300] loss: 1.093
[4,   400] loss: 1.124
[4,   500] loss: 1.077
[4,   600] loss: 1.172
[4,   700] loss: 1.167
[4,   800] loss: 1.075
[5,   100] loss: 1.066
[5,   200] loss: 1.044
[5,   300] loss: 1.057
[5,   400] loss: 1.067
[5,   500] loss: 1.045
[5,   600] loss: 1.132
[5,   700] loss: 1.135
[5,   800] loss: 1.035
Finished Training


In [18]:
correct = 0
total = 0
with torch.no_grad():
    net.eval()
    for i in range(len(x_test)):
        inputs, labels =torch.unsqueeze(x_test[i], 0).to(device).float(), torch.unsqueeze(y_test[i], 0).to(device)
        outputs, (hn, cn) = net(inputs)
        output = torch.mean(outputs, dim=1)  
        #print(inputs)
        print(output)
        _, predicted = torch.max(output.data, 1)
        print(predicted)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
final = 100 * correct / total
print('Accuracy on the test set: %d %%' % (final))

tensor([[-6.0773, -2.6571, -2.0613,  1.0869,  1.9190,  0.1081, -2.9969]])
tensor([4])
tensor([[-7.9946, -3.6186, -2.6556,  1.7467,  2.3851, -0.4765, -4.3830]])
tensor([4])
tensor([[-5.0270, -2.5029, -1.5327,  1.2578,  0.7767,  0.1048, -2.6059]])
tensor([3])
tensor([[-6.2161, -2.7991, -2.0840,  1.1434,  1.7831,  0.2237, -3.0527]])
tensor([4])
tensor([[-7.5548, -3.5459, -2.3874,  1.9479,  2.0439, -0.8438, -4.4658]])
tensor([4])
tensor([[-8.0933, -3.6407, -2.8047,  1.5400,  2.3070,  0.0439, -4.1144]])
tensor([4])
tensor([[-5.4212, -2.2722, -2.2242,  0.2066,  1.5678,  1.7872, -1.5237]])
tensor([5])
tensor([[-8.6763, -3.9870, -2.8921,  2.0557,  2.5123, -0.8182, -4.9384]])
tensor([4])
tensor([[-4.8633, -2.4356, -1.3560,  1.5155,  1.0495, -0.7573, -3.0892]])
tensor([3])
tensor([[-6.4433, -3.2139, -1.8610,  1.9750,  1.4001, -0.9848, -4.0811]])
tensor([3])
tensor([[-5.9610, -2.7898, -1.8459,  1.4719,  1.5774, -0.3874, -3.3380]])
tensor([4])
tensor([[-7.5407, -3.3804, -2.5903,  1.4779,  2.2148, 

tensor([[-7.3381, -3.4708, -2.4676,  1.6662,  1.7316, -0.1516, -3.9013]])
tensor([4])
tensor([[-4.2333, -1.7129, -1.7544,  0.0419,  1.2838,  1.6605, -1.0077]])
tensor([5])
tensor([[-7.7827, -3.6305, -3.0223,  0.8721,  1.4243,  1.8258, -2.8742]])
tensor([5])
tensor([[-5.4786, -2.4768, -1.7691,  1.1117,  1.5823,  0.0220, -2.7923]])
tensor([4])
tensor([[-5.7385, -2.8138, -1.6746,  1.6263,  1.2360, -0.5363, -3.3745]])
tensor([3])
tensor([[-5.4171, -2.6025, -1.5837,  1.5096,  1.4807, -0.7399, -3.3075]])
tensor([3])
tensor([[-8.6589, -3.9144, -2.9806,  1.7533,  2.4509, -0.1686, -4.5463]])
tensor([4])
tensor([[-7.6707, -3.4822, -2.5412,  1.5945,  2.1977, -0.1518, -4.0499]])
tensor([4])
tensor([[-5.1135, -2.3985, -1.8328,  0.7222,  1.0302,  0.9558, -2.0407]])
tensor([4])
tensor([[-6.0500, -2.6714, -2.3115,  0.6359,  1.6333,  1.2070, -2.2748]])
tensor([4])
tensor([[-5.3330, -2.4661, -1.7004,  1.2468,  1.5614, -0.3167, -2.8990]])
tensor([4])
tensor([[-7.6714, -3.4926, -2.5341,  1.7865,  2.3903, 